apiVersion: v1
kind: ConfigMap
metadata:
  name: machine-agent-config
data:
  APPDYNAMICS_CONTROLLER_HOST_NAME: "<HOSTNAME>.saas.appdynamics.com"
  APPDYNAMICS_CONTROLLER_PORT: "443"
  APPDYNAMICS_AGENT_ACCOUNT_NAME: "<ACCOUNT_NAME>"
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: "true"
  APPDYNAMICS_HTTP_LISTENER: "true"
  APPDYNAMICS_HTTP_LISTENER_PORT: "8080"
  APPDYNAMICS_AGENT_HIERARCHY_PATH: "HTTP_TEST|Machine1"
  APPDYNAMICS_AGENT_APPLICATION_NAME: "HTTP_TEST"
  APPDYNAMICS_AGENT_CREATE_NODE_IF_ABSENT: "true"
  APPDYNAMICS_AGENT_NODE_NAME: "HTTP_TEST"
  APPDYNAMICS_AGENT_TIER_NAME: "HTTP_TEST"
  APPDYNAMICS_HTTP_PROXY_HOST: ""
  APPDYNAMICS_HTTP_PROXY_PORT: ""
  APPDYNAMICS_HTTP_PROXY_USER: ""
  APPDYNAMICS_HTTP_PROXY_PASSWORD_FILE: ""
  APPDYNAMICS_AGENT_MAX_METRICS: "10000"
  APPDYNAMICS_AGENT_LOG_DIR: "/logs"